all:
  children:
    k8s_hosts:

k8s_hosts:
  children:
    k8s_cp:
      vars:
        cp_vip: 10.0.0.100
        api_dest_port: 4200
        api_src_port: 6443
        role: master
        keepalived_interface: ens160
        keepalived_priority: 100
      hosts:
        k8s-cp1:
          keepalived_state: MASTER
          keepalived_priority: 101
        k8s-cp2:
          keepalived_state: BACKUP
        k8s-cp3:
          keepalived_state: BACKUP
    k8s_node:
      vars:
        role: worker
      hosts:
        k8s-node1:
        k8s-node2:
        k8s-node3:
  vars:
    ansible_user: ubuntu
    ansible_password: UbuntuPwd123
    ansible_become_password: UbuntuPwd123

...

