---
- name: disable swap in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\s*none\s*swap\s*.*)'
    replace: '# \1'

- name: disable swap by swapoff
  shell: swapoff -a

- name: create modules-load.d/k8s.conf
  file:
    path: /etc/modules-load.d/k8s.conf
    state: touch

- name: update modules-load.d/k8s.conf
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    block: |
          overlay
          br_netfilter

- name: run modeprobe
  shell: |
          sudo modprobe overlay
          sudo modprobe br_netfilter

- name: create sysctl configuration file for cri
  file:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    state: touch

- name: configure sysctl for cri
  blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

- name: apply sysctl
  shell: sysctl --system


- name: install k8s GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: create k8s repo
  copy:
    src: files/k8s.list
    dest: /etc/apt/sources.list.d/

- name: install kubelet and kubectl
  apt:
    update_cache: yes
    state: present
    pkg:
      - kubectl
      - kubelet
      - kubeadm

# - name: install kubeadm for cp
#   apt:
#     state: present
#     pkg:
#       - kubeadm
  # when: '"sat_k8s_cp" in group_names'

...